// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Turizm_Yonetim_Sistemi.DataAccessLayer.Concrete;

#nullable disable

namespace Turizm_Yonetim_Sistemi.DataAccessLayer.Migrations
{
    [DbContext(typeof(DemoContext))]
    partial class DemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Bilet", b =>
                {
                    b.Property<int>("BiletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BiletID"));

                    b.Property<int>("KoltukNo")
                        .HasColumnType("int");

                    b.Property<int>("MusteriID")
                        .HasColumnType("int");

                    b.Property<int>("SeferID")
                        .HasColumnType("int");

                    b.HasKey("BiletID");

                    b.HasIndex("MusteriID");

                    b.HasIndex("SeferID");

                    b.ToTable("Bilets", (string)null);
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Firma", b =>
                {
                    b.Property<int>("FirmaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FirmaID"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FirmaID");

                    b.ToTable("Firmas", (string)null);
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.FirmaGorevlisi", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<string>("MailAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciID");

                    b.HasIndex("FirmaID");

                    b.ToTable("Gorevlis", (string)null);
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Kampanya", b =>
                {
                    b.Property<int>("KampanyaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KampanyaID"));

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KampanyaID");

                    b.HasIndex("FirmaID");

                    b.ToTable("Kampanyas", (string)null);
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Musteri", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciID");

                    b.ToTable("Musteris", (string)null);
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Maas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PersonelTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("PersonelID");

                    b.ToTable("Personels", (string)null);
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.RotaBilgisi", b =>
                {
                    b.Property<int>("RotaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RotaID"));

                    b.Property<string>("KalkisYeri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarisYeri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RotaID");

                    b.ToTable("RotaBilgisis", (string)null);
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Sefer", b =>
                {
                    b.Property<int>("SeferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeferID"));

                    b.Property<decimal>("BiletSatisFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("KalkisZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("RotaBilgisiID")
                        .HasColumnType("int");

                    b.Property<int>("RotaID")
                        .HasColumnType("int");

                    b.Property<int>("TasitID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VarisZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("SeferID");

                    b.HasIndex("RotaBilgisiID");

                    b.HasIndex("TasitID");

                    b.ToTable("Sefers", (string)null);
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Tasit", b =>
                {
                    b.Property<int>("TasitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TasitID"));

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<bool>("KullanimDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TasitTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TasitID");

                    b.HasIndex("FirmaID");

                    b.ToTable("Tasits", (string)null);
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Terminal", b =>
                {
                    b.Property<int>("TerminalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerminalID"));

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Long")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TerminalID");

                    b.ToTable("Terminals", (string)null);
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Vardiya", b =>
                {
                    b.Property<int>("VardiyaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VardiyaID"));

                    b.Property<DateTime>("CmtBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CmtBitis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CrsBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CrsBitis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CumBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CumBitis")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrsBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PrsBitis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PzrBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PzrBitis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PztBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PztBitis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SaliBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SaliBitis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VardiyaBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VardiyaBitisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("VardiyaID");

                    b.HasIndex("PersonelID");

                    b.ToTable("Vardiyas", (string)null);
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Bilet", b =>
                {
                    b.HasOne("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Musteri", "musteri")
                        .WithMany()
                        .HasForeignKey("MusteriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Sefer", "sefer")
                        .WithMany()
                        .HasForeignKey("SeferID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("musteri");

                    b.Navigation("sefer");
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.FirmaGorevlisi", b =>
                {
                    b.HasOne("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Firma", "firma")
                        .WithMany()
                        .HasForeignKey("FirmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("firma");
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Kampanya", b =>
                {
                    b.HasOne("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Firma", "firma")
                        .WithMany()
                        .HasForeignKey("FirmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("firma");
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Sefer", b =>
                {
                    b.HasOne("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.RotaBilgisi", "Rota")
                        .WithMany()
                        .HasForeignKey("RotaBilgisiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Tasit", "Tasit")
                        .WithMany()
                        .HasForeignKey("TasitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");

                    b.Navigation("Tasit");
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Tasit", b =>
                {
                    b.HasOne("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Firma", "firma")
                        .WithMany()
                        .HasForeignKey("FirmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("firma");
                });

            modelBuilder.Entity("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Vardiya", b =>
                {
                    b.HasOne("Turizm_Yonetim_Sistemi.EntityLayer.Concrete.Personel", "personel")
                        .WithMany()
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("personel");
                });
#pragma warning restore 612, 618
        }
    }
}
